// Constants and helpers ported verbatim from the web app (index.html logic block).
export const ADMOB={appId:'ca-app-pub-1294432140413899~2920845178',banner:'ca-app-pub-1294432140413899/7378045065',reward:'ca-app-pub-1294432140413899/5243845473'};
export const CATS=['All','Planets','Moons','Stars','Small Bodies','Galaxies','Nebulae','Phenomena','Universe','Missions'];
export const NF=[['Latest',''],['ISRO','isro'],['Launches','launch'],['NASA','nasa'],['SpaceX','spacex'],['Mars','mars'],['Moon','moon'],['ISS','space station'],['Webb','webb']];
export const ago=d=>{const s=(Date.now()-new Date(d))/1000;if(s<3600)return Math.max(1,Math.round(s/60))+'m ago';if(s<86400)return Math.round(s/3600)+'h ago';return Math.round(s/86400)+'d ago';};
export const F=(s,o)=>String(s||'').replace(/\{(\w+)\}/g,(_,k)=>o[k]);
export const DAY=()=>{const d=new Date();return Math.floor((d-d.getTimezoneOffset()*6e4)/864e5);};
export const rng=seed=>()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296;};
export const LETTERS=['A','B','C','D'];
export const LEVELS=[[1,'Easy'],[2,'Medium'],[3,'Hard']];
export const RANKS=[['Cadet',0],['Pilot',20],['Navigator',50],['Commander',100],['Astronaut',180],['Legend',300]];
export const BADGES=[['first','First Launch','Finish your first quiz'],['perfect','Perfect Orbit','Score 5/5 on any quiz'],['hard','Hard Vacuum','Finish a Hard quiz'],['streak3','On a Roll','Keep a 3-day quiz streak'],['streak7','Week in Orbit','Keep a 7-day quiz streak'],['reader','Explorer','Read 10 encyclopedia topics'],['collector','Collector','Save 5 items'],['sky','Night Watcher','Check tonight’s sky'],['iss','Spotter','Track the ISS live'],['share','Ambassador','Share a card with a friend']];
export const PLANETS=[['mercury','Mercury','#a8a49c',2439,0.241],['venus','Venus','#e3c58f',6052,0.615],['earth','Earth','#6fa3e0',6371,1],['mars','Mars','#d2704a',3390,1.881],['jupiter','Jupiter','#d9b48a',69911,11.86],['saturn','Saturn','#e8d29a',58232,29.46],['uranus','Uranus','#9fd8de',25362,84.01],['neptune','Neptune','#5b7fdc',24622,164.8]];
export const PCOL={moon:'#e9e4d6'};PLANETS.forEach(p=>PCOL[p[0]]=p[2]);
export const GRAV=[['The Moon',.166,'moon'],['Mercury',.38,'mercury'],['Venus',.904,'venus'],['Mars',.379,'mars'],['Jupiter',2.528,'jupiter'],['Saturn',1.065,'saturn'],['Uranus',.886,'uranus'],['Neptune',1.137,'neptune'],['Pluto',.063,'pluto'],['Titan',.138,'titan'],['Europa',.134,'europa'],['The Sun',27.9,'sun']];
export const ECLIPSES=[['2026-08-12','Total solar eclipse','Greenland, Iceland, Spain'],['2026-08-28','Partial lunar eclipse','Americas, Europe, Africa'],['2027-02-06','Annular solar eclipse','South America, Atlantic, Africa'],['2027-02-20','Penumbral lunar eclipse','Americas, Europe, Africa, Asia'],['2027-08-02','Total solar eclipse','Spain, North Africa, Egypt, Arabia'],['2027-08-17','Penumbral lunar eclipse','Pacific, Americas'],['2028-01-12','Partial lunar eclipse','Americas, Europe, Africa'],['2028-01-26','Annular solar eclipse','South America, Spain, Portugal'],['2028-07-06','Partial lunar eclipse','Europe, Africa, Asia, Australia'],['2028-07-22','Total solar eclipse','Australia, New Zealand'],['2028-12-31','Total lunar eclipse','Europe, Asia, Australia']];
export const WALL_THEMES=[['Nebulae','nebula hubble'],['Galaxies','galaxy webb'],['Earth','earth from space station'],['Planets','saturn cassini'],['Aurora','aurora'],['Stars','star cluster']];
export const OTD_FALLBACK=[{year:1957,text:'Sputnik 1, the first artificial satellite, is launched by the Soviet Union (4 Oct).'},{year:1961,text:'Yuri Gagarin becomes the first human in space aboard Vostok 1 (12 Apr).'},{year:1969,text:'Apollo 11 lands on the Moon; Neil Armstrong takes the first step (20 Jul).'}];
export const SPACE_RE=/\b(space|nasa|satellite|rocket|astronaut|cosmonaut|spacecraft|orbit|orbital|lunar|planet|comet|telescope|apollo|soyuz|shuttle|voyager|sputnik|vostok|gemini|probe|asteroid|galaxy|supernova|spacex|esa|roscosmos|iss|mir|skylab|hubble|moon landing|isro|chandrayaan|mangalyaan|aryabhata|pslv|gslv|gaganyaan|aditya-l1|sriharikota)\b/i;
export const TZ_CITIES={'Asia/Kolkata':[28.61,77.21,'New Delhi'],'Asia/Calcutta':[28.61,77.21,'New Delhi'],'Asia/Karachi':[24.86,67.01,'Karachi'],'Asia/Dhaka':[23.81,90.41,'Dhaka'],'Asia/Dubai':[25.2,55.27,'Dubai'],'Asia/Singapore':[1.35,103.82,'Singapore'],'Asia/Tokyo':[35.68,139.69,'Tokyo'],'Asia/Shanghai':[31.23,121.47,'Shanghai'],'Asia/Jakarta':[-6.2,106.85,'Jakarta'],'Asia/Manila':[14.6,120.98,'Manila'],'Europe/London':[51.51,-0.13,'London'],'Europe/Paris':[48.86,2.35,'Paris'],'Europe/Berlin':[52.52,13.4,'Berlin'],'Europe/Madrid':[40.42,-3.7,'Madrid'],'Europe/Rome':[41.9,12.5,'Rome'],'Europe/Moscow':[55.76,37.62,'Moscow'],'Africa/Lagos':[6.52,3.38,'Lagos'],'Africa/Cairo':[30.04,31.24,'Cairo'],'Africa/Johannesburg':[-26.2,28.05,'Johannesburg'],'Africa/Nairobi':[-1.29,36.82,'Nairobi'],'America/New_York':[40.71,-74.01,'New York'],'America/Chicago':[41.88,-87.63,'Chicago'],'America/Denver':[39.74,-104.99,'Denver'],'America/Los_Angeles':[34.05,-118.24,'Los Angeles'],'America/Mexico_City':[19.43,-99.13,'Mexico City'],'America/Sao_Paulo':[-23.55,-46.63,'São Paulo'],'America/Bogota':[4.71,-74.07,'Bogotá'],'America/Argentina/Buenos_Aires':[-34.6,-58.38,'Buenos Aires'],'America/Toronto':[43.65,-79.38,'Toronto'],'Australia/Sydney':[-33.87,151.21,'Sydney'],'Australia/Melbourne':[-37.81,144.96,'Melbourne'],'Pacific/Auckland':[-36.85,174.76,'Auckland']};
export const DEF_LOC=(()=>{let tz='';try{tz=Intl.DateTimeFormat().resolvedOptions().timeZone;}catch(e){}const c=TZ_CITIES[tz];if(c)return{lat:c[0],lon:c[1],name:c[2]+' (approx.)'};const off=-new Date().getTimezoneOffset()/60;return{lat:30,lon:Math.max(-180,Math.min(180,off*15)),name:'Your time zone (approx.)'};})();
export const LANGS=[['en','English','English'],['hi','Hindi','हिन्दी'],['es','Spanish','Español']];
export const TX={
en:{explore:'Explore',news:'News',today:'Today',sky:'Sky',quiz:'Quiz',more:'More',newsTitle:'Space News',todayTitle:'Today in Space',skyTitle:'Tonight’s Sky',quizTitle:'Daily Quiz',moreTitle:'More',search:'Search planets, stars, missions…',loadMore:'Load more stories',readFull:'Read full article',save:'☆ Save',saved:'★ Saved',remind:'Remind me',next:'Next question →',results:'See results',back:'← More',settings:'Settings',appearance:'Appearance',themeSystem:'Match phone',themeSystemSub:'Follows your phone’s light/dark setting',themeLight:'Light',themeLightSub:'Bright, easy reading in daylight',themeDark:'Dark',themeDarkSub:'Easy on the eyes at night'},
hi:{explore:'खोजें',news:'समाचार',today:'आज',sky:'आकाश',quiz:'क्विज़',more:'और',newsTitle:'अंतरिक्ष समाचार',todayTitle:'आज अंतरिक्ष में',skyTitle:'आज रात का आकाश',quizTitle:'दैनिक क्विज़',moreTitle:'और',search:'ग्रह, तारे, मिशन खोजें…',loadMore:'और खबरें देखें',readFull:'पूरा लेख पढ़ें',save:'☆ सहेजें',saved:'★ सहेजा गया',remind:'याद दिलाएँ',next:'अगला प्रश्न →',results:'परिणाम देखें',back:'← और',settings:'सेटिंग्स',appearance:'थीम',themeSystem:'फ़ोन जैसा',themeSystemSub:'आपके फ़ोन की लाइट/डार्क सेटिंग के अनुसार',themeLight:'लाइट',themeLightSub:'दिन में पढ़ने के लिए चमकदार',themeDark:'डार्क',themeDarkSub:'रात में आँखों के लिए आरामदायक'},
es:{explore:'Explorar',news:'Noticias',today:'Hoy',sky:'Cielo',quiz:'Quiz',more:'Más',newsTitle:'Noticias espaciales',todayTitle:'Hoy en el espacio',skyTitle:'El cielo esta noche',quizTitle:'Quiz diario',moreTitle:'Más',search:'Buscar planetas, estrellas, misiones…',loadMore:'Cargar más noticias',readFull:'Leer artículo completo',save:'☆ Guardar',saved:'★ Guardado',remind:'Recordarme',next:'Siguiente →',results:'Ver resultados',back:'← Más',settings:'Ajustes',appearance:'Apariencia',themeSystem:'Como el teléfono',themeSystemSub:'Sigue el modo claro/oscuro del teléfono',themeLight:'Claro',themeLightSub:'Brillante, ideal de día',themeDark:'Oscuro',themeDarkSub:'Descansa la vista de noche'}};
export const hav=(a,b,c,d)=>{const r=Math.PI/180,x=Math.sin((c-a)*r/2)**2+Math.cos(a*r)*Math.cos(c*r)*Math.sin((d-b)*r/2)**2;return 12742*Math.asin(Math.sqrt(x));};
export const moonDisc=frac=>{const waxing=frac<0.5,il=(1-Math.cos(2*Math.PI*frac))/2;return{halfLeft:waxing?'50%':'0%',ellW:(Math.abs(Math.cos(2*Math.PI*frac))*100).toFixed(1)+'%',ellC:il<0.5?'var(--moon-dark)':'#e9e4d6'};};
export const THEMES={dark:{'--bg':'#07080c','--bg-rgb':'7,8,12','--surface':'#11131a','--surface2':'#0d0f14','--cell':'#0f1117','--nav':'#0a0b10','--hover':'#161922','--text':'#eceef3','--text2':'#c9ccd4','--text3':'#b8bcc6','--muted':'#8a90a0','--muted2':'#6b7180','--stripe1':'#151821','--ink':'255,255,255','--moon-dark':'#232733','--toggle-off':'#2a2e38','--line-strong':'#3a3f4c','--err-bg':'#1a1216','--err':'#ffb3b3','--amber':'#f0b46a','--blue':'#8fb8ff','--green':'#7fd6a0','--red':'#ff9b9b','--on-accent':'#1a1206','--on-blue':'#08101f'},
light:{'--bg':'#f6f5f2','--bg-rgb':'246,245,242','--surface':'#ffffff','--surface2':'#efeee9','--cell':'#fbfaf8','--nav':'#ffffff','--hover':'#f0efea','--text':'#15171d','--text2':'#33363f','--text3':'#4a4e58','--muted':'#646975','--muted2':'#80858f','--stripe1':'#ecebe6','--ink':'10,12,20','--moon-dark':'#2b2f3a','--toggle-off':'#d6d5d0','--line-strong':'#c4c6cc','--err-bg':'#fbeaea','--err':'#b3261e','--amber':'#a2600f','--blue':'#2757b8','--green':'#1d7f49','--red':'#c0392b','--on-accent':'#ffffff','--on-blue':'#ffffff'}};

// Locale-aware date helpers (web version used a mutable LOCALE global)
export const fmt=(d,L)=>new Date(d).toLocaleDateString(L,{month:'short',day:'numeric',year:'numeric'});
export const fmtD=(d,L)=>new Date(d).toLocaleDateString(L,{month:'short',day:'numeric'});
export const fmtT=(d,L)=>new Date(d).toLocaleTimeString(L,{hour:'numeric',minute:'2-digit'});
export const pickLevel=(QUIZ,day,lvl)=>{const pool=QUIZ.map((q,i)=>i).filter(i=>(QUIZ[i][5]||2)===lvl);const r=rng(day*9973+lvl*131);for(let i=pool.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[pool[i],pool[j]]=[pool[j],pool[i]];}return pool.slice(0,5);};
export const httpsify=u=>typeof u==='string'?u.replace(/^http:/,'https:'):u;